### ISSUE TITLE
后面前端是否会实现动态路由

### ISSUE THREAD

**Issue by hu1045274719** [continew-org/continew-admin#1]
### Feature 描述

后面前端是否会实现动态路由

### 描述一下您想要的解决方案

后面前端是否会实现动态路由

### 确认

- [X] 阅读[文档](https://github.com/Charles7c/continew-admin#readme)
- [X] 搜索是否有其他人提交过类似的 issue，如果对应 issue 尚未解决，您可以先订阅关注该 issue（为了方便后来者查找问题解决方法，请尽量避免创建重复的 issue）

**Comment by Charles7c** [comment]
这个肯定是会的。目前由于工作原因，每天晚上仅有2-3个小时 + 不确定的周末来完善项目，所以孵化方向稍微偏向了能快速完成的功能模块，总体孵化进度比较慢。
