### ISSUE TITLE
[Bug] 代码生成工具：换成pgsql后，代码生成的sql脚本没有改变

### ISSUE THREAD

**Issue by luoqiz** [continew-org/continew-admin#106]
### Bug 描述

换成pgsql后，代码生成的sql脚本没有改变

### 复现步骤

切换pgsql

### 预期结果

生成pgsql的插入脚本

### 环境信息

```markdown
ContiNew Admin version(s): 3.4.1
```

### 确认

- [X] 阅读[文档](https://continew.top/admin/other/faq.html)
- [X] 根据报错信息百度或 Google 一下
- [X] 搜索是否有其他人提交过类似的 issue，如果对应 issue 尚未解决，您可以先订阅关注该 issue（为了方便后来者查找问题解决方法，请尽量避免创建重复的 issue）

**Comment by Charles7c** [comment]
代码生成的 SQL 模板自己改一下，把 MySQL 的删除，把 PgSQL 注释去掉。
![4492d0babd02218f312d1f78b2bbeb4](https://github.com/user-attachments/assets/290fd5eb-8f10-49af-adc5-aac4afef9820)
