### ISSUE TITLE
[Bug] 没有办法实现下拉框懒加载或者现实问题

### ISSUE THREAD

**Issue by Stars-XK** [continew-org/continew-admin#113]
### Bug 描述

![image](https://github.com/user-attachments/assets/1bcaed98-6dd1-4cdb-a49f-ca56e3fcafe9)
由于是经过feng'zhua封装的代码，这里添加change事件应该怎么添加呢

### 复现步骤

第一个问题：
![image](https://github.com/user-attachments/assets/56373593-4881-4135-9256-66430a4f265f)
这里的配置问题，我看了好久的参数，页面启动的时候获取后端传来的分类数据，然后没办法渲染到下拉框
![image](https://github.com/user-attachments/assets/0b0e53c4-09c5-446d-bb75-c926881acb2c)

第二个问题：
下拉框如果是懒加载怎么实现

### 预期结果

我想把树结构数据展示到下拉框，或者实现懒加载树结构数据，

### 环境信息

```markdown
ContiNew Admin version(s):
```

### 确认

- [X] 阅读[文档](https://continew.top/admin/other/faq.html)
- [X] 根据报错信息百度或 Google 一下
- [X] 搜索是否有其他人提交过类似的 issue，如果对应 issue 尚未解决，您可以先订阅关注该 issue（为了方便后来者查找问题解决方法，请尽量避免创建重复的 issue）

**Comment by Charles7c** [comment]
3.x 项目前端采用 [gi-demo前端模板](https://github.com/lin-97/gi-demo)，有 Gi 组件相关的前端问题可以单独在此项目咨询。
> 依照我的经验，可以看看 gi-demo 项目里有没有示例。
