### ISSUE TITLE
[Bug] 【feat(system/client): 新增客户端管理】 这个版本提交后，验证码没有验证了

### ISSUE THREAD

**Issue by muchen2018** [continew-org/continew-admin#115]
### 请您确认

- [X] 尝试最新 dev 分支代码，仍有相同问题
- [X] 阅读[使用指南](https://continew.top/admin/intro/what-is.html)
- [X] 查找[常见问题](https://continew.top/faq.html)
- [X] 根据报错信息（自行翻译英文）百度或 Google 一下
- [X] 搜索是否有其他人提交过类似的 Issue，如果对应 Issue 尚未解决，您可以先订阅关注该 Issue（为了方便后来者查找问题解决方法，请尽量避免创建重复的 Issue）
- [X] 阅读源码并在 IDE 中进行断点调试

### Bug 描述

代码中没有校验验证码

### 复现步骤

代码中没有校验验证码

### 预期结果

验证验证码

### 环境信息

```markdown
ContiNew Admin version(s):3.4.1
```

**Comment by Charles7c** [comment]
等晚上看一下，这个 PR 还没梳理呢，dev 是开发版本，会有不稳定因素。

**Comment by Charles7c** [comment]
应该好了，昨晚初步梳理了一轮。https://github.com/continew-org/continew-admin/commit/c90e80e9d72eba173df586e7f12a0c9378c82ec9
