### ISSUE TITLE
[Bug] 最新版本的 3.4.1 Snail Job 默认的配置是是关闭的，但是在关闭的情况下运行项目是会启动的Snail Job的

### ISSUE THREAD

**Issue by tcwxcn** [continew-org/continew-admin#117]
### 请您确认

- [X] 尝试最新 dev 分支代码，仍有相同问题
- [X] 阅读[使用指南](https://continew.top/admin/intro/what-is.html)
- [X] 查找[常见问题](https://continew.top/faq.html)
- [X] 根据报错信息（自行翻译英文）百度或 Google 一下
- [X] 搜索是否有其他人提交过类似的 Issue，如果对应 Issue 尚未解决，您可以先订阅关注该 Issue（为了方便后来者查找问题解决方法，请尽量避免创建重复的 Issue）
- [X] 阅读源码并在 IDE 中进行断点调试

### Bug 描述

在默认情况下直接启动，如果数据没有snail_job的数据库是启动不起来的

![image](https://github.com/user-attachments/assets/50bdd889-6731-4289-80f8-9767f285dc4b)

在数据库手动添加这个数据库，项目可以正常运行，但是Snail Job也启动了

![image](https://github.com/user-attachments/assets/cd75ab81-951a-42b9-bfa2-a27e722b82a5)

下载的最新的3.4.1版本，配置文件中采用的是默认配置

### 复现步骤

直接启动项目

### 预期结果

在帮助文档中，有说明默认情况下，dev 环境的任务调度配置是被关闭的，以防止控制台一直打印连接错误，所以当你有需要使用时，需要启用任务调度相关配置。 

### 环境信息

```markdown
ContiNew Admin version(s):3.4.1
```

**Comment by Charles7c** [comment]
你启动错了项目，那是 Snail Job 服务端，ContiNewAdminApplication 才是真正的启动入口。
在线文档：https://continew.top/admin/intro/quick-start.html
