### ISSUE TITLE
最新提交的版本postgre 中的sql 初始化脚本缺失-- 初始化客户端数据

### ISSUE THREAD

**Issue by sunscorch** [continew-org/continew-admin#118]
最新提交的版本postgre 中的sql 初始化脚本缺失-- 初始化客户端数据
main_data.sql

-- 初始化客户端数据
INSERT INTO `sys_client`
(`id`, `client_id`, `client_key`, `client_secret`, `auth_type`, `client_type`, `active_timeout`, `timeout`, `status`, `create_user`, `create_time`)
VALUES
(1, 'ef51c9a3e9046c4f2ea45142c8a8344a', 'pc', 'dd77ab1e353a027e0d60ce3b151e8642', '[\"ACCOUNT\", \"EMAIL\", \"PHONE\", \"SOCIAL\"]', 'PC', 1800, 86400, 1, 1, NOW());

**Comment by sunscorch** [comment]
测试使用 这个脚本 可以fix:
INSERT INTO "sys_client" ( "id", "client_id", "client_key", "client_secret", "auth_type", "client_type", "active_timeout", "timeout", "status", "create_user", "create_time" )
VALUES ( 1, 'ef51c9a3e9046c4f2ea45142c8a8344a', 'pc', 'dd77ab1e353a027e0d60ce3b151e8642', '["ACCOUNT", "EMAIL", "PHONE", "SOCIAL"]', 'PC', 1800, 86400, 1, 1, NOW() );

**Comment by Charles7c** [comment]
好的，补的时候漏掉了，可以提个 PR 啊大佬
