### ISSUE TITLE
偶发性登录成功后不跳转

### ISSUE THREAD

**Issue by LvHuaiSheng** [continew-org/continew-admin#13]
### Bug 描述

使用前端路由，在登录成功后偶发性不跳转首页，在刷新后再次登录才会跳转成功

### 复现步骤

使用Firefox或Chrome登录即可复现，附演示版测试截图（登录成功提示了“欢迎使用”，nprogress也从左到右瞬间100%）但路由无变化：
![图片](https://github.com/Charles7c/continew-admin/assets/35132878/86391d6c-d3bd-4a27-979c-356ca7aa0cac)

### 预期结果

登录成功后可正常跳转到首页

### 环境信息

使用（1.0.1-SNAPSHOT）问题存在；
看框架的演示版（1.1.0-SNAPSHOT）问题依然存在；

### 确认

- [x] 阅读[文档](https://github.com/Charles7c/continew-admin#readme)
- [X] 根据报错信息百度或 Google 一下
- [X] 搜索是否有其他人提交过类似的 issue，如果对应 issue 尚未解决，您可以先订阅关注该 issue（为了方便后来者查找问题解决方法，请尽量避免创建重复的 issue）

**Comment by Charles7c** [comment]
此问题是项目所采用的前端底座 Arco Design Pro Vue [#241](https://github.com/arco-design/arco-design-pro-vue/issues/241) 的已知问题，目前社区解释是开启了 Mock 所致，可以在 continew-admin-ui/src/utils/setup-mock.ts 中关闭 Mock 后再试一试。

> 可参见在线文档/常见问题：https://doc.charles7c.top/faq.html#%E5%89%8D%E7%AB%AF%E9%9C%80%E8%A6%81%E9%87%8D%E5%A4%8D%E7%99%BB%E5%BD%95
