### ISSUE TITLE
Java版本应该使用哪个呢

### ISSUE THREAD

**Issue by lihuacai168** [continew-org/continew-admin#24]
### Feature 描述

在文档中似乎没看到对应的Java版本,有点小疑惑

### 描述一下您想要的解决方案

麻烦标注一下支持的Java版本

### 确认

- [X] 阅读[文档](https://doc.charles7c.top/faq.html)
- [X] 搜索是否有其他人提交过类似的 issue，如果对应 issue 尚未解决，您可以先订阅关注该 issue（为了方便后来者查找问题解决方法，请尽量避免创建重复的 issue）

**Comment by Charles7c** [comment]
v1.3.0 及之前版本都是使用的 Java 8。
