### ISSUE TITLE
代码生成页面显示之后整体失去响应

### ISSUE THREAD

**Issue by ryanxia2016** [continew-org/continew-admin#27]
### Bug 描述

菜单栏里点击代码生成菜单，再点击其他菜单，页面无反应，除非刷新页面

### 复现步骤

1菜单栏里点击代码生成菜单
2再点击其他菜单，页面无反应，除非刷新页面

### 预期结果

其他菜单可正常点击响应

### 环境信息

JDK21，最新代码

### 确认

- [X] 阅读[文档](https://doc.charles7c.top/faq.html)
- [X] 根据报错信息百度或 Google 一下
- [X] 搜索是否有其他人提交过类似的 issue，如果对应 issue 尚未解决，您可以先订阅关注该 issue（为了方便后来者查找问题解决方法，请尽量避免创建重复的 issue）

**Comment by Charles7c** [comment]
感谢反馈，已经复现定位了，是由前两天新增 `生成预览` 功能时引起的，今天晚上我修复一下，也欢迎多多 PR 或进微信群多多沟通。
