### ISSUE TITLE
代码生成目录不存在异常

### ISSUE THREAD

**Issue by java668** [continew-org/continew-admin#30]
### Bug 描述

配置代码生成配置填写前端路径，前端路径不存在会抛异常：cn.hutool.core.io.IORuntimeException: IORuntimeException: IOException: No such file or directory
<img width="1789" alt="image" src="https://github.com/Charles7c/continew-admin/assets/124699758/85677080-3c1b-4aef-9015-3c317309340b">
<img width="1792" alt="image" src="https://github.com/Charles7c/continew-admin/assets/124699758/17dda7a0-fb27-41d7-87cb-9666009e2c14">

### 复现步骤

1、配置代码生成配置填写前端路径，点击保存
2、点击生成代码

### 预期结果

配置代码生成配置填写前端路径，前端路径不存在自动创建目录，成功生成代码

### 环境信息

JDK17,
continew-admin-2.2.0

### 确认

- [X] 阅读[文档](https://doc.charles7c.top/admin/other/faq.html)
- [X] 根据报错信息百度或 Google 一下
- [X] 搜索是否有其他人提交过类似的 issue，如果对应 issue 尚未解决，您可以先订阅关注该 issue（为了方便后来者查找问题解决方法，请尽量避免创建重复的 issue）

**Comment by Charles7c** [comment]
在目前设计中，前端路径必须存在，目的是将生成的 vue、api 文件输出到前端项目的正确目录。页面配置提示了要求输入前端项目 view 目录的路径，此路径是前端项目结构解析和生成的关键路径。
不过，提示不太友好，晚上我加个校验提示。
