### ISSUE TITLE
postman 请求接口响应乱码&上传文件响应乱码

### ISSUE THREAD

**Issue by java668** [continew-org/continew-admin#31]
### Bug 描述

用postman请求接口响应乱码，如图：
<img width="1349" alt="image" src="https://github.com/Charles7c/continew-admin/assets/124699758/b62fd833-b77c-46e2-8d5b-091eb562b968">
上传文件响应乱码：
![Uploading image.png…]()

### 复现步骤

postman请求接口必现以及用Arco upalod上传文件响应乱码必现

### 预期结果

响应正常json数据

### 环境信息

v2.2.0 java17

### 确认

- [X] 阅读[文档](https://doc.charles7c.top/admin/other/faq.html)
- [X] 根据报错信息百度或 Google 一下
- [X] 搜索是否有其他人提交过类似的 issue，如果对应 issue 尚未解决，您可以先订阅关注该 issue（为了方便后来者查找问题解决方法，请尽量避免创建重复的 issue）

**Comment by Charles7c** [comment]
此问题前段时间在 Swagger 文档中测试接口发现过，由于前端对接使用时未出现阻塞问题被暂时忽略了。

错误描述：执行接口，接口响应会以文件流形式返回
1.在浏览器地址栏调用接口，会自动下载文件，打开为响应内容乱码。
2.如果是在 Postman 等 API 工具中则可以直接看到内容乱码。
3.响应类型为 application/cbor

错误起源初步推测是 v2.1.0 拆分 ContiNew Starter 后的某项改动引发的。
错误原因初步推测：
1.过滤器是否存在问题，系统中目前存在多个过滤器会对请求、响应体进行处理，例如：系统日志过滤器会对请求及响应体进行流复制
2.涉及到本应该为 JSON 响应类型，却被转换为其他类型，考虑是否与 Jackson 配置有关
3. `HttpMessageConverter` 是否存在问题
4.引入的某个组件配置是否存在问题

晚上，我先根据这几项推测排查一下。
