### ISSUE TITLE
OSS文件上传

### ISSUE THREAD

**Issue by weirantongxue** [continew-org/continew-admin#32]
### Feature 描述

文件上传到OSS的时候.好像不会在桶里自动创建文件夹,直接传到桶的主目录,是不是可以考虑用日期分割作为目录.方便后期服务迁移的时候能够更好的选中文件指定文件迁移.

### 描述一下您想要的解决方案

文件上传到OSS的时候.好像不会在桶里自动创建文件夹,直接传到桶的主目录,是不是可以考虑用日期分割作为目录.方便后期服务迁移的时候能够更好的选中文件指定文件迁移.

### 确认

- [X] 阅读[文档](https://doc.charles7c.top/admin/intro/require.html)
- [X] 搜索是否有其他人提交过类似的 issue，如果对应 issue 尚未解决，您可以先订阅关注该 issue（为了方便后来者查找问题解决方法，请尽量避免创建重复的 issue）

**Comment by Charles7c** [comment]
收到
