### ISSUE TITLE
token失效控制台报错

### ISSUE THREAD

**Issue by weirantongxue** [continew-org/continew-admin#34]
### Bug 描述

<img width="1884" alt="image" src="https://github.com/Charles7c/continew-admin/assets/32252943/fd133fb7-bd70-4c82-b882-4a6e6d85645c">

### 复现步骤

登录token失效,或者第一次登录提示token失效的时候会出现控制台报错

### 预期结果

错误异常应该被捕获 返回到前端正确的提示.如果过多的登录失效的控制台的错误日志会太多

### 环境信息

JDK版本:17 项目版本:v2.3.x 

### 确认

- [X] 阅读[文档](https://doc.charles7c.top/admin/other/faq.html)
- [X] 根据报错信息百度或 Google 一下
- [X] 搜索是否有其他人提交过类似的 issue，如果对应 issue 尚未解决，您可以先订阅关注该 issue（为了方便后来者查找问题解决方法，请尽量避免创建重复的 issue）

**Comment by Charles7c** [comment]
Token 失效报错似乎是正常的吧？页面也有对应提示的。
