### ISSUE TITLE
贵项目禁用  @accessors(chain = true) 的原因是什么，遇到过什么暗坑吗？

### ISSUE THREAD

**Issue by uncarbon97** [continew-org/continew-admin#35]
移除所有的 @Accessors(chain = true)，并全局配置禁止使用 ([76c6546](https://github.com/Charles7c/continew-admin/commit/76c65463c2e5ddf0c90fa1622fd86706a4373c80))

**Comment by Charles7c** [comment]
最经典的是使用 EasyExcel 时会出现问题，可参考：https://github.com/alibaba/easyexcel/issues/2610。
此项注解由于会改变 get/set 结构，不加限制的滥用，极易引发问题，所以最终决定从全局规范上加以制约。

**Comment by uncarbon97** [comment]
好的，谢谢讲解，长见识了
