### ISSUE TITLE
代码生成实体类路径bug

### ISSUE THREAD

**Issue by weirantongxue** [continew-org/continew-admin#39]
### Bug 描述

在生成实体类的时候,如果数据库修改或者调整完字段顺序,生成字段在实体类,依旧是最后一位.还有一个问题是代码生成@Query注解路径有问题. 使用admin版本是v2.4.0  start使用的版本是v1.4.1  

### 复现步骤

代码生成顺序
![56824ea9abc630a6b213c3c49bb2880](https://github.com/Charles7c/continew-admin/assets/32252943/1c4bfc39-e0d2-469b-bd84-18ed772584c8)
![af5af016c14f76d15b6d36d2d95194d](https://github.com/Charles7c/continew-admin/assets/32252943/45aca347-4836-4ab3-8634-d836d99f5e34)

路径问题
代码生成的路径是
import top.charles7c.continew.starter.data.mybatis.plus.query.Query;
import top.charles7c.continew.starter.data.mybatis.plus.query.QueryType;
实际导入路径是
import top.charles7c.continew.starter.data.core.annotation.Query;
import top.charles7c.continew.starter.data.core.enums.QueryType;

### 预期结果

无

### 环境信息

使用admin版本是v2.4.0  start使用的版本是v1.4.1

### 确认

- [X] 阅读[文档](https://doc.charles7c.top/admin/other/faq.html)
- [X] 根据报错信息百度或 Google 一下
- [X] 搜索是否有其他人提交过类似的 issue，如果对应 issue 尚未解决，您可以先订阅关注该 issue（为了方便后来者查找问题解决方法，请尽量避免创建重复的 issue）

**Comment by Charles7c** [comment]
你是在原来版本的 ContiNew Admin 上升级了新的 ContiNew Starter，注意更新代码生成模板。
