### ISSUE TITLE
代码生成多选以及下载

### ISSUE THREAD

**Issue by weirantongxue** [continew-org/continew-admin#40]
### Feature 描述

希望代码生成中可以同时选中多张表进行生成.生成完成可以弹出下载链接直接下载到本地

### 描述一下您想要的解决方案

这样可以更好的解决多人协作的问题.还有就是基于admin后台开发别的服务进行集成的时候要.这项目是单体可能这个模块不属于admin模块.以至于生成的代码不能直接写入对应项目的文件夹.

### 确认

- [X] 阅读[文档](https://doc.charles7c.top/admin/intro/require.html)
- [X] 搜索是否有其他人提交过类似的 issue，如果对应 issue 尚未解决，您可以先订阅关注该 issue（为了方便后来者查找问题解决方法，请尽量避免创建重复的 issue）

**Comment by Charles7c** [comment]
好的，加上同步字段自动排序问题，我也记录了。欢迎多多反馈代码生成器问题，它还很稚嫩。

**Comment by Charles7c** [comment]
> 好的，加上同步字段自动排序问题，我也记录了。欢迎多多反馈代码生成器问题，它还很稚嫩。

同步时自动获取最新字段排序已经加上了，https://github.com/Charles7c/continew-admin/commit/89546deced78f83daca7ac0ba2e7d3d8cd101d0c 欢迎测试反馈。

**Comment by weirantongxue** [comment]
> > 好的，加上同步字段自动排序问题，我也记录了。欢迎多多反馈代码生成器问题，它还很稚嫩。
> 
> 同步时自动获取最新字段排序已经加上了，[89546de](https://github.com/Charles7c/continew-admin/commit/89546deced78f83daca7ac0ba2e7d3d8cd101d0c) 欢迎测试反馈。
辛苦辛苦...赞

**Comment by Charles7c** [comment]
多选下载功能欢迎 PR，:)
