### ISSUE TITLE
存储设置

### ISSUE THREAD

**Issue by weirantongxue** [continew-org/continew-admin#41]
### Feature 描述

建议加入存储设置,可以对不同的云厂商key还有信息进行可视化配置

### 描述一下您想要的解决方案

<img width="1636" alt="image" src="https://github.com/Charles7c/continew-admin/assets/32252943/ffbb4865-4633-4abf-9198-47edf882c79c">
<img width="1125" alt="image" src="https://github.com/Charles7c/continew-admin/assets/32252943/33403e5a-bda8-4534-a96c-bd4ff579ef50">

### 确认

- [X] 阅读[文档](https://doc.charles7c.top/admin/intro/require.html)
- [X] 搜索是否有其他人提交过类似的 issue，如果对应 issue 尚未解决，您可以先订阅关注该 issue（为了方便后来者查找问题解决方法，请尽量避免创建重复的 issue）

**Comment by Charles7c** [comment]
是这个吗？
![image](https://github.com/Charles7c/continew-admin/assets/25446948/971f57d6-63f6-417c-9b9c-f05c2cc1b032)
![image](https://github.com/Charles7c/continew-admin/assets/25446948/8515c36c-9bfd-4505-b1cd-7e75058d2a73)

**Comment by weirantongxue** [comment]
> 是这个吗？ ![image](https://private-user-images.githubusercontent.com/25446948/310387357-971f57d6-63f6-417c-9b9c-f05c2cc1b032.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MDc0ODIsIm5iZiI6MTcwOTcwNzE4MiwicGF0aCI6Ii8yNTQ0Njk0OC8zMTAzODczNTctOTcxZjU3ZDYtNjNmNi00MTdjLTliOWMtZjA1YzJjYzFiMDMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDA2Mzk0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlNDA1NzJlYmJlOWE1YzQxM2I5NDJmNTZlMTk5NmQ0MmRlZDdmM2ZiZTZhMzNmZjM1NGY1NjA5ZWRjZTZjNDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IV1qK-2APz8GvRT5lwOQIYldNF_fdn272U5h3TjYgdc) ![image](https://private-user-images.githubusercontent.com/25446948/310387318-8515c36c-9bfd-4505-b1cd-7e75058d2a73.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3MDc0ODIsIm5iZiI6MTcwOTcwNzE4MiwicGF0aCI6Ii8yNTQ0Njk0OC8zMTAzODczMTgtODUxNWMzNmMtOWJmZC00NTA1LWIxY2QtN2U3NTA1OGQyYTczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDA2Mzk0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2MGI0ODlkMzk1ZTVkYTMzNGU5YTM0NDhhODRkMTUxZGY4ZTdlMTAxYWQ0YjNjYzQ1NTFiOWZiMzkxMDNlMGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TE0AzTeCRrUuwl3I4-Pr2H4xE_6tepIlELsXMtZIobs)

是的是的,不好意思 我没注意到 哈哈哈

**Comment by Charles7c** [comment]
不过这个按钮确实太小了，完了我给调成大按钮

**Comment by Charles7c** [comment]
![image](https://github.com/Charles7c/continew-admin/assets/25446948/4096cb3f-ca31-44cc-8087-b7b0ce8a7acf)
