### ISSUE TITLE
代码生成

### ISSUE THREAD

**Issue by weirantongxue** [continew-org/continew-admin#42]
### Bug 描述

![e8062ad273fbe7108a70870eeea94cd](https://github.com/Charles7c/continew-admin/assets/32252943/d5bea4f3-2dab-4a2e-8456-09ec88b6eaea)
代码生成的这个页面,分页展示问题.

### 复现步骤

![63136f3430b1e921b256e7a4294a45b](https://github.com/Charles7c/continew-admin/assets/32252943/6806fd97-cb06-4a97-8a58-f735cc7a069a)

翻下一页的时候下一页只有一条数据

### 预期结果

无

### 环境信息

jdk:17 框架最新版本

### 确认

- [X] 阅读[文档](https://doc.charles7c.top/admin/other/faq.html)
- [X] 根据报错信息百度或 Google 一下
- [X] 搜索是否有其他人提交过类似的 issue，如果对应 issue 尚未解决，您可以先订阅关注该 issue（为了方便后来者查找问题解决方法，请尽量避免创建重复的 issue）

**Comment by Charles7c** [comment]
问题定位了，和近期抽取 generator 模块有关，配置抽取出来后，开发环境没问题，但由于打包配置的原因，导致线上环境配置失效，晚上我优化一下这部分的配置。
所以说，SNAPSHOT 快照版就是不稳定 :\，欢迎大佬在使用快照版时多多反馈问题，**并标注好快照版本，方便快速定位，例如：ContiNew Admin 2.5.0-SNAPSHOT。** 
![image](https://github.com/Charles7c/continew-admin/assets/25446948/6de171f1-5fdb-4c44-ac32-83b4f5a7c498)

**Comment by weirantongxue** [comment]
> 问题定位了，和近期抽取 generator 模块有关，配置抽取出来后，开发环境没问题，但由于打包配置的原因，导致线上环境配置失效，晚上我优化一下这部分的配置。 所以说，SNAPSHOT 快照版就是不稳定 :\，欢迎大佬在使用快照版时多多反馈问题，**并标注好快照版本，方便快速定位，例如：ContiNew Admin 2.5.0-SNAPSHOT。** ![image](https://private-user-images.githubusercontent.com/25446948/311578781-6de171f1-5fdb-4c44-ac32-83b4f5a7c498.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxMzExNTMsIm5iZiI6MTcxMDEzMDg1MywicGF0aCI6Ii8yNTQ0Njk0OC8zMTE1Nzg3ODEtNmRlMTcxZjEtNWZkYi00YzQ0LWFjMzItODNiNGY1YTdjNDk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzExVDA0MjA1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhZTkyNjA3MzBkMDI5ZTJmZGIwZmY1NDhiYWE0MzgxMjAyZTk3NDNhZTZkY2JlYzZlNDA0NjA4MTgwYTFiMDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.x8UlW8atK5-2bH9QTCyA6eOSoU8L9X-58XCpRwgcDrY)

收到,我下次标注指定的版本,感谢~
