### ISSUE TITLE
关于项目中私人starter

### ISSUE THREAD

**Issue by Alexzkh** [continew-org/continew-admin#44]
### Feature 描述

里面有些starter的源码可以开源不？例如日志的starter

### 描述一下您想要的解决方案

希望开源

### 确认

- [X] 阅读[文档](https://doc.charles7c.top/admin/intro/require.html)
- [X] 搜索是否有其他人提交过类似的 issue，如果对应 issue 尚未解决，您可以先订阅关注该 issue（为了方便后来者查找问题解决方法，请尽量避免创建重复的 issue）

**Comment by Charles7c** [comment]
ContiNew Starter 是开源的，见https://github.com/Charles7c/continew-starter

**Comment by Alexzkh** [comment]
yeah i know thanks for your apply...
