### ISSUE TITLE
字典

### ISSUE THREAD

**Issue by weirantongxue** [continew-org/continew-admin#46]
### Bug 描述

/api/common/dict/{code}  在前端获取字典信息的时候.字典对应的code创建了值,但是接口只能查询到两个

去掉这个方法上的缓存注解直接走数据库没问题
@CachePenetrationProtect
    @CacheRefresh(refresh = 3600, stopRefreshAfterLastAccess = 7200)
    @Cached(key = "#code", name = CacheConstants.DICT_KEY_PREFIX)

### 复现步骤

<img width="1674" alt="image" src="https://github.com/Charles7c/continew-admin/assets/32252943/6ec3bd82-a645-453d-a7a2-063603a6a5fe">
<img width="1388" alt="image" src="https://github.com/Charles7c/continew-admin/assets/32252943/b1a83c50-157f-4f0d-a0f4-4ada76f2597b">

### 预期结果

返回对应值

### 环境信息

jdk 17   dev分支

### 确认

- [X] 阅读[文档](https://doc.charles7c.top/admin/other/faq.html)
- [X] 根据报错信息百度或 Google 一下
- [X] 搜索是否有其他人提交过类似的 issue，如果对应 issue 尚未解决，您可以先订阅关注该 issue（为了方便后来者查找问题解决方法，请尽量避免创建重复的 issue）

**Comment by Charles7c** [comment]
3.0.x 已去除字典缓存
