### ISSUE TITLE
[Task] 优化验证码超时显示效果，超时后显示已过期请刷新

### ISSUE THREAD

**Issue by Charles7c** [continew-org/continew-admin#54]
### Description

优化图形验证码超时显示效果，超时后显示已过期请刷新

 ![image](https://github.com/Charles7c/continew-admin/assets/25446948/46eecfc0-f5e0-457e-898f-493e2403a1b6)

### Task List

- [x] 获取图形验证码接口增加 `expireTime` 过期时长（秒）字段返回 
- [x] 图形验证码展示增加定时器，超过指定时长则显示如图所示内容

**Comment by NGbetrue** [comment]
我来雕一下这朵花
