### ISSUE TITLE
Charles7c大佬什么时候补充完整的开发文档，比如如何新增一个模块，如何新增一个功能。

### ISSUE THREAD

**Issue by ZhangChaoZhong** [continew-org/continew-admin#64]
### Feature 描述

大胆预测一波，Charles7c大佬这个项目爆火🔥🔥🔥。
真的很好用，CRUD真的是非常好用！！！
但是相关开发文档还是比较少，我也希望我可以pr，但是我这个菜鸡有些代码可能还看不太懂。

### 描述一下您想要的解决方案

无

### 描述一下您考虑过的替代方案

无

### 额外补充

无

### 确认

- [X] 阅读[文档](https://continew.top/admin/intro/require.html)
- [X] 搜索是否有其他人提交过类似的 issue，如果对应 issue 尚未解决，您可以先订阅关注该 issue（为了方便后来者查找问题解决方法，请尽量避免创建重复的 issue）
- [X] 您是否愿意为您提出的 Feature 提交 PR？

**Comment by Charles7c** [comment]
感谢支持，文档我也有在加哈，时间有限，目前一周至少加一篇或更新一篇。
非常欢迎提交 PR 啊，只要不是代码爆炸的 PR 我都接受了，因为如果不合理，我会重构改掉部分代码的。
