### ISSUE TITLE
[Feature] 希望能加入多语言国际化选择功能

### ISSUE THREAD

**Issue by voishion** [continew-org/continew-admin#75]
### Feature 描述

我希望能加入多语言国际化选择功能

### 描述一下您想要的解决方案

无

### 确认

- [X] 阅读[文档](https://continew.top/admin/intro/require.html)
- [X] 搜索是否有其他人提交过类似的 issue，如果对应 issue 尚未解决，您可以先订阅关注该 issue（为了方便后来者查找问题解决方法，请尽量避免创建重复的 issue）
- [ ] 您是否愿意为您提出的 Feature 提交 PR？

**Comment by Charles7c** [comment]
我们有计划针对后端的错误信息和响应信息进行国际化，预计在近几个版本，前端则暂时无此计划。

**Comment by Charles7c** [comment]
错误信息已支持国际化。
