### ISSUE TITLE
系统管理-存储管理

### ISSUE THREAD

**Issue by liusir008** [continew-org/continew-admin#76]
### Bug 描述

新建存储，选择兼容S3协议存储，使用minio，提交后端校验提示私有密钥长度不能超过255个字符。

### 复现步骤

新建存储，选择兼容S3协议存储，使用minio，提交后端校验提示私有密钥长度不能超过255个字符。

### 预期结果

正常新建或修改存储

### 环境信息

```markdown
ContiNew Admin version(s):v3.1.0
```

### 确认

- [X] 阅读[文档](https://continew.top/admin/other/faq.html)
- [X] 根据报错信息百度或 Google 一下
- [X] 搜索是否有其他人提交过类似的 issue，如果对应 issue 尚未解决，您可以先订阅关注该 issue（为了方便后来者查找问题解决方法，请尽量避免创建重复的 issue）

**Comment by Charles7c** [comment]
好的，应该是和前段时间做了加密传参有关，加密后的串超过255个字符。
