### ISSUE TITLE
希望能支持Flux 响应式编程

### ISSUE THREAD

**Issue by weirantongxue** [continew-org/continew-admin#80]
### Feature 描述

在框架使用spring-boot-starter-webflux 无法使用响应式.或者流式输出.
导致集成spring-ai提供的对应start包,也无法使用流式输出.

### 描述一下您想要的解决方案

我排查了好久,找不到为什么,啊哈哈哈,.我新建一个空的springboot3.0X的项目是可以的.
操作如下.希望大佬有空的时候帮忙看一下.

1. 新建springboot3.0X
2. 引入maven

```
  <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webflux</artifactId>
  </dependency>
```

3. 编写测试接口

```
    @GetMapping(value = "/stream", produces = MediaType.TEXT_EVENT_STREAM_VALUE)
    public Flux<String> stream() {
        return Flux.interval(Duration.ofSeconds(1))
                .map(sequence -> "Flux - " + LocalTime.now().toString());
    }
```

4.响应输出
![image](https://github.com/user-attachments/assets/53eebd64-1e45-4b05-98dd-57274bc4077e)

### 确认

- [X] 阅读[文档](https://continew.top/admin/intro/require.html)
- [X] 搜索是否有其他人提交过类似的 issue，如果对应 issue 尚未解决，您可以先订阅关注该 issue（为了方便后来者查找问题解决方法，请尽量避免创建重复的 issue）
- [X] 您是否愿意为您提出的 Feature 提交 PR？

**Comment by Charles7c** [comment]
之前是因为 log 组件的过滤器导致的问题，ContiNew Starter v2.4.0 给 log 组件新增了一个 excludePatterns 配置，可以放行不需要过滤的路由。
