### ISSUE TITLE
[Bug] 启动报错：Access denied for user 'root'@'localhost' (using password: YES)

### ISSUE THREAD

**Issue by youan-dev** [continew-org/continew-admin#81]
### Bug 描述

Caused by: com.mysql.cj.exceptions.CJException: Access denied for user 'root'@'localhost' (using password: YES)

1、检查过mysql5.7的 账号密码，权限 ，都是正确的。
2、也尝试改过数据库连接参数 ：useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai&tinyInt1isBit=false 
3、根据文档一步步操作的。

### 复现步骤

配置完了数据库和redis，启动就报错。

### 预期结果

为啥其他朋友的不报错。

### 环境信息

```markdown
ContiNew Admin version(s);最新版
```

### 确认

- [X] 阅读[文档](https://continew.top/admin/other/faq.html)
- [X] 根据报错信息百度或 Google 一下
- [X] 搜索是否有其他人提交过类似的 issue，如果对应 issue 尚未解决，您可以先订阅关注该 issue（为了方便后来者查找问题解决方法，请尽量避免创建重复的 issue）

**Comment by Charles7c** [comment]
这个错误提示很明显是密码错误（root@localhost），再检查下吧亲，或者进群描述下，这种错误没有第二种情况。
