### ISSUE TITLE
有没有升级手册

### ISSUE THREAD

**Issue by C-L-STARK** [continew-org/continew-admin#82]
### Feature 描述

[Feature] 有没有升级手册

### 描述一下您想要的解决方案

[Feature] 有没有升级手册

### 描述一下您考虑过的替代方案

[Feature] 有没有升级手册

### 额外补充

[Feature] 有没有升级手册

### 确认

- [X] 阅读[文档](https://continew.top/admin/intro/require.html)
- [X] 搜索是否有其他人提交过类似的 issue，如果对应 issue 尚未解决，您可以先订阅关注该 issue（为了方便后来者查找问题解决方法，请尽量避免创建重复的 issue）
- [X] 您是否愿意为您提出的 Feature 提交 PR？

**Comment by Charles7c** [comment]
Admin 项目理论上不支持线性升级，它本质上是一个模板。
详情查看：https://continew.top/admin/other/update.html
