### ISSUE TITLE
[Bug] 角色查询关键字参数

### ISSUE THREAD

**Issue by CangJieStore** [continew-org/continew-admin#85]
### Feature 描述

后端RoleQuery 类参数name 改为description

### 描述一下您想要的解决方案

后端RoleQuery 类参数name 改为description

### 确认

- [X] 阅读[文档](https://continew.top/admin/intro/require.html)
- [X] 搜索是否有其他人提交过类似的 issue，如果对应 issue 尚未解决，您可以先订阅关注该 issue（为了方便后来者查找问题解决方法，请尽量避免创建重复的 issue）
- [X] 您是否愿意为您提出的 Feature 提交 PR？

**Comment by Charles7c** [comment]
之前调整查询风格时，漏掉了角色的后端改动。晚上修复一下
