### ISSUE TITLE
请问这个工具可以作为公司商用项目的脚手架吗

### ISSUE THREAD

**Issue by sunl888** [continew-org/continew-admin#87]
### Feature 描述

无

### 描述一下您想要的解决方案

无

### 确认

- [X] 阅读[文档](https://continew.top/admin/intro/require.html)
- [X] 搜索是否有其他人提交过类似的 issue，如果对应 issue 尚未解决，您可以先订阅关注该 issue（为了方便后来者查找问题解决方法，请尽量避免创建重复的 issue）
- [ ] 您是否愿意为您提出的 Feature 提交 PR？

**Comment by Charles7c** [comment]
![image](https://github.com/user-attachments/assets/5137dafe-8c0e-472a-b7c7-4875d7735ce4)

项目 | 协议 | 是否可商用
-- | -- | --
ContiNew Admin | Apache-2.0 开源许可协议 | 可开发商业应用
ContiNew Starter | LGPL-3.0 开源许可协议 | 通过 Maven/Gradle 等依赖方式开发商业应用

总结：没问题
