### ISSUE TITLE
如何在项目中新建一个模块？内部有豁免的接口controller并在swagger中？

### ISSUE THREAD

**Issue by hyoutom** [continew-org/continew-admin#88]
### Feature 描述

请问大佬，如何在项目中新建一个模块？内部有豁免的接口controller并在swagger中？

### 描述一下您想要的解决方案

有文档吗？

### 确认

- [X] 阅读[文档](https://continew.top/admin/intro/require.html)
- [X] 搜索是否有其他人提交过类似的 issue，如果对应 issue 尚未解决，您可以先订阅关注该 issue（为了方便后来者查找问题解决方法，请尽量避免创建重复的 issue）
- [X] 您是否愿意为您提出的 Feature 提交 PR？

**Comment by Charles7c** [comment]
介绍了如何新增一个模块：https://continew.top/admin/intro/develop.html
