### ISSUE TITLE
[Bug] 部门筛选

### ISSUE THREAD

**Issue by weirantongxue** [continew-org/continew-admin#89]
### Bug 描述

不同部门有相同子节点名称的时候搜索名称,只能搜到一个

### 复现步骤

![WechatIMG25838](https://github.com/user-attachments/assets/8d877da7-e164-44ae-bcca-40ad9ea0fc2d)
![WechatIMG25839](https://github.com/user-attachments/assets/0684d7e8-13b1-4fb8-9118-26d3cf650f1e)

### 预期结果

能通过名字搜索到正确结果

### 环境信息

```markdown
ContiNew Admin version(s):
```

### 确认

- [X] 阅读[文档](https://continew.top/admin/other/faq.html)
- [X] 根据报错信息百度或 Google 一下
- [X] 搜索是否有其他人提交过类似的 issue，如果对应 issue 尚未解决，您可以先订阅关注该 issue（为了方便后来者查找问题解决方法，请尽量避免创建重复的 issue）

**Comment by Charles7c** [comment]
经过慎重考虑，已重构树型列表过滤为前端过滤，并支持显示其上级树。
