### ISSUE TITLE
[Feature] 在只有一级菜单时，可以在tab内打开，而非全屏路由；

### ISSUE THREAD

**Issue by LvHuaiSheng** [continew-org/continew-admin#92]
### Feature 描述

在只有一级菜单时，可以在tab内打开，而非全屏路由

### 描述一下您想要的解决方案

在只有一级菜单时，可以在tab内打开，而非全屏路由；可在菜单配置中选择全屏打开还是tab打开页面

### 确认

- [X] 阅读[文档](https://continew.top/admin/intro/require.html)
- [X] 搜索是否有其他人提交过类似的 issue，如果对应 issue 尚未解决，您可以先订阅关注该 issue（为了方便后来者查找问题解决方法，请尽量避免创建重复的 issue）
- [ ] 您是否愿意为您提出的 Feature 提交 PR？

**Comment by Charles7c** [comment]
目前的策略是只有一个菜单的目录不显示，所以你完全可以给它配一个目录来解决你的需求。
![image](https://github.com/user-attachments/assets/3e26da09-a486-460c-a8ca-a02b96d83971)
如果你有更深入需求，可在 Gi Demo 项目中提一下此 issue。
